# Generated by Django 5.2.1 on 2025-05-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerrequest',
            name='phone',
            field=models.CharField(default='Not provided', max_length=20),
            preserve_default=False,
        ),
    ]
