# Generated by Django 5.2.1 on 2025-05-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('date_posted', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
