# Generated by Django 5.2.1 on 2025-05-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_blogpost_date_posted_alter_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('Education', 'Education'), ('Child Protection', 'Child Protection'), ('Health and Nutrition', 'Health and Nutrition'), ('Economic Empowerment', 'Economic Empowerment'), ('Adolescent SRHR', 'Adolescent SRHR')], default='Education', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='Education', upload_to='blog_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
