# Generated by Django 5.2.1 on 2025-05-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_blogpost_category_alter_blogpost_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('quote', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(upload_to='team_photos/')),
                ('category', models.CharField(choices=[('leadership', 'Leadership'), ('programs', 'Programs'), ('finance', 'Finance & Admin'), ('volunteers', 'Volunteers'), ('advisory', 'Advisory Board')], max_length=20)),
            ],
        ),
    ]
