# Generated by Django 5.2.1 on 2025-05-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donation_alter_blogpost_image_alter_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='tx_ref',
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_email',
            field=models.EmailField(default='anon@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='donation',
            name='transaction_reference',
            field=models.CharField(default='TEMP-REF', max_length=100, unique=True),
        ),
    ]
