# Generated by Django 5.2.1 on 2025-06-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='category',
            field=models.CharField(choices=[('education', 'Education and Awareness'), ('health', 'Community Health'), ('empowerment', 'Economic Empowerment'), ('environment', 'Environmental Protection'), ('rights', 'Human Rights and Governance')], default='education', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
