# Generated by Django 5.2 on 2025-07-08 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogpost_contactmessage_donation_programcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.programcategory', verbose_name='Program Category'),
        ),
    ]
